# Generated by Django 4.2.6 on 2023-10-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContatoSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome: ')),
                ('sobrenome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobrenome:')),
                ('numero_de_telefone', models.CharField(max_length=20, verbose_name='Telefone: ')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email: ')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
